# Generated by Django 3.2.4 on 2021-06-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/student_assignments'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
