# Generated by Django 3.2.4 on 2021-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_deadlines_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='assignment_in_category', to='dashboard.categories'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='notes_in_category', to='dashboard.categories'),
        ),
    ]
