# Generated by Django 3.2.6 on 2021-10-16 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_assignments_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='background',
            field=models.ImageField(default='uploads/profile_background/default.jpg', upload_to='uploads/profile_background'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='location',
            field=models.CharField(default='Assigno', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default='Assigno User', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures'),
        ),
    ]
