# Generated by Django 3.2.6 on 2021-10-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20211016_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(choices=[('', 'Choose Your Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Rather Not Say', 'Rather Not Say')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
