# Generated by Django 3.2.6 on 2021-10-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20211017_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='test', unique=True),
            preserve_default=False,
        ),
    ]
