# Generated by Django 3.2.6 on 2021-10-18 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20211016_1342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0003_forum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum_post',
            name='assignments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_shared_on', to='dashboard.assignments'),
        ),
        migrations.AlterField(
            model_name='forum_post',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_shared_on', to='dashboard.notes'),
        ),
    ]
